# try
# except 
# else
# finally 

# try:
#     print(x)
# except NameError:
#     print('La varibale x no esta definida')
# except:
#     print('Otra cosa fue mal')


# else

# try:
#     print('Hola Python')
# except:
#     print('Algo fue mal')
# else:
#     print('Nada fue mal')


# finally
# try:
#     print(x)
# except:
#     print('Algo fue mal')
# finally:
#     print('El try.. except termino!')


